config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'

  root    'welcome#index'
  get     'welcome/index'
  get     '/login',         to: 'sessions#new'
  post    '/login',         to: 'sessions#create'
  delete  '/logout',        to: 'sessions#destroy'
  get     '/contact',       to: 'contact#contact'
  get     '/signup',        to: 'users#new'
  get     '/languages',     to: 'languages#index'
  get 'password_resets/new'
  get 'password_resets/edit'

  resources :languages
  resources :dictionaries_categories
  resources :dictionaries
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/language.rb
class Language < ApplicationRecord

  has_many :dictionaries
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    id = current_user
    if params[:term]
      @languages = Language.joins(:dictionaries)
                       .where(dictionaries: {user_id: id})
                       .where('lower(name) LIKE ?', "%#{params[:term]}%".downcase)
                       .group(:name)
                       .order("count(languages.name) DESC")
                       .count
    else
      @languages = Language.joins(:dictionaries)
                       .where(dictionaries: {user_id: id})
                       .group(:name)
                       .order("count(languages.name) DESC")
                       .count
    end
    @languages_ids = Language.joins(:dictionaries).select(:id)
  end

  private

  # whitelist the parameters to prevent wrongful mass assignment
  def dictionary_params
    params.require(:language).permit(:term)
  end

end

app/helpers/language_helper.rb
module LanguageHelper
end

app/views/languages/index.html.erb
<% provide(:title, "Dictionaries") %>

<div class="row align-items-center">
  <div class="col-6">
    <h1 class="display-4">
      <%= link_to 'Dictionaries', languages_path %>
    </h1>
  </div>

  <% if @languages.size == 0 %>
      <div class="col-8" id="first_dictionary">
        <%= link_to "Create your first dictionary now!", dictionaries_path, class: "btn btn-outline-success btn-lg btn-block" %>
      </div>
  <% else %>
      <div class="col-6 ">
        <%= link_to "New dictionary", dictionaries_path, class: "btn btn-outline-secondary float-right margin_bottom margin_top" %>
      </div>
  <% end %>

</div>

<% @languages.each_slice(2) do |row| %>
    <div class="card-deck">
      <% row.each do |language| %>
          <% language_id = @languages_ids.find_by(name: language[0])[:id] %>
          <div class="card margin_bottom">

            <%= link_to(dictionaries_path(language: language_id)) do %>
                <div class="card-block">
                  <h4 class="card-title">
                    <% language_id = @languages_ids.find_by(name: language[0])[:id] %>
                    <%= language[0] %>
                  </h4>
                  <p class="card-text">
                    <% last = Dictionary.where(user_id: @current_user, language_id: language_id).order(created_at: :desc).first %>
                    <small class="text-muted">Latest addition
                      <% day_count = (Date.today - last.created_at.to_date).to_i %>
                      <% if day_count == 0 %>
                          today
                      <% else %>
                          <%= pluralize(day_count.to_s, 'day') + " ago" %>
                      <% end %>
                    </small>
                  </p>
                </div>
                <div class="card-footer">
                  <small class="text-muted text-right"><%= pluralize(language[1], 'word') %></small>
                </div>
            <% end %>

          </div>
      <% end %>
    </div>
<% end %>