config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'

  root    'welcome#index'
  get     'welcome/index'
  get     '/login',         to: 'sessions#new'
  post    '/login',         to: 'sessions#create'
  delete  '/logout',        to: 'sessions#destroy'
  get     '/contact',       to: 'contact#contact'
  get     '/signup',        to: 'users#new'
  get     '/languages',     to: 'languages#index'
  get 'password_resets/new'
  get 'password_resets/edit'

  resources :languages
  resources :dictionaries_categories
  resources :dictionaries
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  has_many :categories
  has_many :dictionaries_categories, dependent: :destroy
  accepts_nested_attributes_for :dictionaries_categories
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController

  include DictionariesCategoriesHelper

  def index
    search_pattern = 'lower(word) LIKE ? OR lower(translation) LIKE ?'
    if params[:term]
      if params[:category_id]
        @dictionaries = Dictionary
                            .joins(:dictionaries_categories)
                            .where(dictionaries_categories: {category_id: params[:category_id]})
                            .where(user_id: current_user.id)
                            .where(language_id: params[:language])
                            .where(search_pattern, "%#{params[:term]}%".downcase, "%#{params[:term]}%".downcase)
                            .order(created_at: :desc)
                            .paginate(page: params[:page]).per_page(30)
      else
        @dictionaries = Dictionary
                            .where(user_id: current_user.id)
                            .where(language_id: params[:language])
                            .where(search_pattern, "%#{params[:term]}%".downcase, "%#{params[:term]}%".downcase)
                            .order(created_at: :desc)
                            .paginate(page: params[:page]).per_page(30)
      end
    else
      if params[:category_id]
        @dictionaries = Dictionary
                            .joins(:dictionaries_categories)
                            .where(dictionaries_categories: {category_id: params[:category_id]})
                            .where(user_id: current_user.id)
                            .where(language_id: params[:language])
                            .order(created_at: :desc)
                            .paginate(page: params[:page]).per_page(30)

      else
        @dictionaries = Dictionary
                            .where(user_id: current_user.id)
                            .where(language_id: params[:language])
                            .order(created_at: :desc)
                            .paginate(page: params[:page]).per_page(30)
      end
    end

    @language_list = Language.all
    @categories_list = Category.all

  end

  def show
    @dictionary = Dictionary.find(params[:id])
  end

  def new
    @dictionary = Dictionary.new
  end

  def edit
    @dictionary = Dictionary.find(params[:id])
    @categories_list = Category.all
  end

  def create

    EasyTranslate.api_key = 'AIzaSyDPn-JkZmeKQOWMgjpBBgIRkta3LRQyX-Q'

    if dictionary_params[:word].blank? and dictionary_params[:translation].blank?
      flash[:danger] = "Please fill in word or translation"
      redirect_back fallback_location: dictionaries_path
    else
      @dictionary = Dictionary.create(dictionary_params)
      mother_lang = Language.find(current_user.language_id).name.downcase
      source_dest_lang = Language.find(@dictionary.language_id).name.downcase

      if @dictionary.translation.empty?
        @dictionary.translation = EasyTranslate.translate(@dictionary.word, from: source_dest_lang, to: mother_lang)
      elsif @dictionary.word.empty?
        @dictionary.word = EasyTranslate.translate(@dictionary.translation, from: mother_lang, to: source_dest_lang)
      end

      @dictionary.save

      @dictionaries_category = DictionariesCategory.where(dictionary_id: @dictionary.id, category_id: params[:dictionary][:dictionaries_category][:category_id])
                                   .first_or_create(dictionary_id: @dictionary.id, category_id: params[:dictionary][:dictionaries_category][:category_id])

      flash[:success] = @dictionary.word + " - CREATED"
      redirect_to dictionaries_path(language: @dictionary.language_id)
    end

  end


  def update
    @dictionary = Dictionary.find(params[:id])
    flash[:success] = @dictionary.word + " - EDITED"
    @dictionary.update(dictionary_params)

    @dictionaries_category = DictionariesCategory.where(dictionary_id: @dictionary.id, category_id: params[:dictionary][:dictionaries_category][:category_id])
                                 .first_or_create(dictionary_id: @dictionary.id, category_id: params[:dictionary][:dictionaries_category][:category_id])

    redirect_to edit_dictionary_path(@dictionary)
  end

  def destroy
    @dictionary = Dictionary.find(params[:id])
    flash[:success] = @dictionary.word + " - DELETED"
    @dictionary.destroy
    redirect_back(fallback_location: dictionaries_path)
  end

  private

  # whitelist the parameters to prevent wrongful mass assignment
  def dictionary_params
    params.require(:dictionary).permit(:word, :translation, :user_id, :term, :language_id, :dictionaries_category)
  end

  def dictionaries_categories_params
    params.permit(:category_id, :dictionary_id)
  end

end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_dictionary.html.erb
<tr>
  <td class="text-left"><%= dictionary.word %></td>
  <td class="text-left"><%= dictionary.translation %></td>
  <td class="text-left">
    <% categories_for_word(dictionary.id).each do |cat| %>
        <%= link_to cat.category.name, dictionaries_path(category_id: cat.category.id, language: dictionary.language_id, term: params[:term]), class: "btn btn-sm btn-outline-secondary margin_bottom" %>
    <% end %>
  </td>
  <td>
    <div class="btn-group float-right" role="group" aria-label="Actions">
      <%= link_to 'Details', dictionary_path(dictionary), class: "btn btn-outline-success" %>
      <%= link_to 'Edit', edit_dictionary_path(dictionary), class: "btn btn-outline-info" %>
      <%= link_to 'Delete', dictionary_path(dictionary), method: :delete, class: "btn btn-outline-danger" %>
    </div>
  </td>
</tr>

app/views/dictionaries/_form.html.erb
<%= form_for dictionary do |f| %>
    <div class="form-group">

      <div class="row">
        <div class="col-6">
          <%= f.text_field :word, class: "form-control form-control-lg", placeholder: "Word" %>
        </div>

        <div class="col-6">
          <%= f.text_field :translation, class: "form-control form-control-lg", placeholder: "Translation" %>
          <% if params[:language] %>
              <%= f.hidden_field :language_id, value: params[:language] %>
          <% end %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>
      </div>

      <div class="row">
        <div class="col-6 margin_top">
          <% unless @language_list.nil? %>
              <%= f.select :language_id, @language_list.map {|lang| [lang.name, "#{lang.id}"]}, {selected: params[:language], required: true}, {class: "custom_select"} %>
          <% end %>
        </div>

        <%= f.fields_for :dictionaries_category do |dc| %>
            <div class="col-6 margin_top">
              <% unless @categories_list.nil? %>
                  <%= dc.select :category_id, @categories_list.map {|cat| [cat.name, "#{cat.id}"]}, {prompt: "Select category"}, {class: "custom_select"} %>
              <% end %>
            </div>
        <% end %>

      </div>
      <div class="row">
        <div class="col-12 margin_top">
          <div class="btn-group float-right" role="group" aria-label="Actions">
            <%= f.submit "Save", class: "btn btn-outline-secondary btn-lg" %>
            <% unless @language_list.nil? %>
                <%= f.submit "Translate", class: "btn btn-outline-secondary btn-lg" %>
            <% else %>
                <%= link_to "Back", dictionaries_path(language: @dictionary.language_id), class: "btn btn-outline-secondary btn-lg" %>
            <% end %>
          </div>
        </div>
      </div>

    </div>
<% end %>

app/views/dictionaries/edit.html.erb
<% provide(:title, @dictionary.word) %>
<h1 class="display-4">Edit</h1>

<div>
  <% categories_for_word(@dictionary.id).each do |cat| %>
      <%= link_to cat, method: :delete, class: "btn btn-sm btn-outline-danger margin_bottom", 'aria-label': "Close" do %>
          <span><%= cat.category.name %></span>
          <span aria-hidden="true">&times;</span>
      <% end %>
  <% end %>

  <%= render 'form', dictionary: @dictionary %>
</div>

app/views/dictionaries/index.html.erb
<% provide(:title, "Dictionary") %>

<div class="row align-items-center">
  <div class="col">
    <h1 class="display-4">
      <% if Language.find_by(id: params[:language]) %>
          <%= link_to Language.find_by(id: params[:language]).name, dictionaries_path(language: params[:language]) %>
      <% else %>
          Dictionary
      <% end %>
    </h1>
  </div>

  <div class="col">
    <% if params[:term] %>
        <%= link_to dictionaries_path(language: params[:language], category_id: params[:category_id]), class: "btn btn-outline-danger margin_bottom margin_top margin_left float-right", 'aria-label': "Close" do %>
            <span><%= 'Filter: ' + params[:term] %></span>
            <span aria-hidden="true">&times;</span>
        <% end %>
    <% end %>
    <% if params[:category_id] %>
        <%= link_to dictionaries_path(language: params[:language], term: params[:term]), class: "btn btn-outline-danger margin_bottom margin_top margin_left float-right", 'aria-label': "Close" do %>
            <span><%= 'Filter: ' + Category.find(params[:category_id]).name %></span>
            <span aria-hidden="true">&times;</span>
        <% end %>
    <% end %>
  </div>
</div>

<% # TODO %>
<% # OPTIMIZE %>
<% # FIXME %>

<%= render 'form', dictionary: Dictionary.new %>

<% unless @dictionaries.empty? %>
    <table class="table table-hover">

      <thead>
      <tr>
        <th class="text-left">Word</th>
        <th class="text-left">Translation</th>
        <th class="text-left">Categories</th>
        <th></th>
      </tr>
      </thead>

      <tbody id="dictionaries">
      <%= render @dictionaries %>
      </tbody>

    </table>
<% end %>

<div class="row justify-content-center">
  <%= will_paginate @dictionaries %>
</div>

app/views/dictionaries/index.js.erb
$('#dictionaries').append('<%= escape_javascript render(@dictionaries) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@dictionaries) %>');

app/views/dictionaries/show.html.erb
<% provide(:title, @dictionary.word) %>
<h1 class="display-4">Details</h1>

<table class="table">
  <tr>
    <th class="text-center">Word</th>
    <th class="text-center">Translation</th>
    <th class="text-center">Categories</th>
    <th class="text-center">Created</th>
    <th class="text-center">Last update</th>
  </tr>

  <tr>
    <td class="text-center"><%= @dictionary.word %></td>
    <td class="text-center"><%= @dictionary.translation %></td>
    <td class="text-center">
      <% categories_for_word(@dictionary.id).each do |cat| %>
          <%= link_to cat.category.name,
                      dictionaries_path(category_id: cat.category.id,
                                        language: @dictionary.language_id,
                                        term: params[:term]),
                                        class: "btn btn-sm btn-outline-secondary margin_bottom" %>
      <% end %>
    </td>
    <td class="text-center"><%= @dictionary.created_at.localtime.ctime %></td>
    <td class="text-center"><%= @dictionary.updated_at.localtime.ctime %></td>
  </tr>
</table>

<div class="row">
  <div class="col-12 margin_top">
    <div class="btn-group float-right" role="group" aria-label="Actions">
      <%= link_to "Edit", edit_dictionary_path(@dictionary), class: "btn btn-outline-secondary btn-lg" %>
      <%= link_to "Back", dictionaries_path(language: @dictionary.language_id), class: "btn btn-outline-secondary btn-lg" %>
    </div>
  </div>
</div>