config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'

  root    'welcome#index'
  get     'welcome/index'
  get     '/login',         to: 'sessions#new'
  post    '/login',         to: 'sessions#create'
  delete  '/logout',        to: 'sessions#destroy'
  get     '/contact',       to: 'contact#contact'
  get     '/signup',        to: 'users#new'
  get     '/languages',     to: 'languages#index'
  get 'password_resets/new'
  get 'password_resets/edit'

  resources :languages
  resources :dictionaries_categories
  resources :dictionaries
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :dictionary
end

app/models/dictionaries_category.rb
class DictionariesCategory < ApplicationRecord
  belongs_to :dictionary
  belongs_to :category

  validates :category_id, presence: true
  validates :dictionary_id, presence: true
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  has_many :categories
  has_many :dictionaries_categories, dependent: :destroy
  accepts_nested_attributes_for :dictionaries_categories
end

app/models/language.rb
class Language < ApplicationRecord

  has_many :dictionaries
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :dictionaries

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    # OPTIMIZE move to model user.rb
    if params[:term]
      @users = User.where('lower(name) LIKE ?', "%#{params[:term]}%".downcase)
                   .order(created_at: :desc)
                   .paginate(page: params[:page]).per_page(30)
    else
      @users = User.order(created_at: :desc)
                   .paginate(page: params[:page]).per_page(30)
    end

  end

  def show
    @user = User.find(params[:id])
    @language = Language.find(@user.language_id).name
  end

  def new
    @language_list = Language.all
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      @language_list = Language.all
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])

    @language_list = Language.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :term, :language_id)
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Vouky - Your personal dictionary"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/language_helper.rb
module LanguageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-faded mt-4 footer">
  <div class="container-fluid py-3">
    <div class="row align-items-center">
      <div class="col-6 float-right">
        <small>Copyright © VOUKY since 2017<br>made with  <i class="fa fa-heart" aria-hidden="true"></i><b> by Kattyi</b></small>
      </div>
      <div class="col-6">
        <%= link_to 'Contact', contact_path, class: "btn btn-outline-secondary my-2 my-sm-0 float-right" %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="fixed-top navbar navbar-toggleable-sm navbar-light bg-faded" id="navbar">
    <%= link_to image_tag("header_logo.svg", alt: "Vouky logo", id: "logo"), root_path %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <% if logged_in? %>
            <li class="nav-item"><%= link_to 'Dictionaries', languages_path, class: "nav-link" %></li>
            <li class="dropdown">
              <a class="nav-link dropdown-toggle" type="link" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                <%= current_user.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to "Profile", current_user, class: "dropdown-item" %>
                <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
                <% if current_user.admin? %>
                    <%= link_to "Users", users_path, class: "dropdown-item" %>
                <% end %>
                <div class="dropdown-divider"></div>
                <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
            <li>
              <% if logged_in? %>
                  <% # OPTIMIZE nerob query ked neni v modeli specifikovany search %>
                  <%= form_tag(request.path, method: :get, class: "form-inline my-2 my-lg-0") do %>
                      <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2", placeholder: "Search" %>
                      <%= hidden_field_tag :language, params[:language] %>
                      <% if params[:category_id] %>
                          <%= hidden_field_tag :category_id, params[:category_id] %>
                      <% end %>
                      <%= submit_tag 'Search', class: "btn btn-outline-secondary my-2 my-sm-0" %>
                  <% end %>
              <% end %>
            </li>
        <% else %>
            <li class="nav-item"><%= link_to 'Log in', login_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Sign up', signup_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_pagination.html.erb
<div class="row">
  <div class="btn-group col-sm-12 justify-content-end" role="group" aria-label="Navigation buttons">
    <%= link_to_prev_page table, '<<', class: "btn btn-outline-secondary" %>
    <%= link_to_next_page table, '>>', class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> | Vouky</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'vouky.ico' %>

  <% if Rails.env.production? %>
      <script type="text/javascript">
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-101203107-1', 'auto');
      </script>
  <% end %>

  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>